FROM node:20-alpine
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate --schema ./prisma/schema.prisma
RUN chown -R node:node /home/node/app
USER node
EXPOSE 3000
CMD [ "npm", "start", "start:dev" ]
